name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3


      - name: Deploy to Render
        run: | 
          curl --request POST \
          --url https://api.render.com/v1/services/srv-crnbq3l6l47c73ad3lc0/deploys \
          --header 'accept: application/json' \
          --header 'content-type: application/json' \
          --data '
          {
            "clearCache": "do_not_clear"
          }'